kind: pipeline
name: default

steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: max-heidinger-cache
    path: /cache
  settings:
    restore: true
    mount:
      - ./node_modules

- name: build-site
  image: node
  commands:
  - npm install
  - npm run build

- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: max-heidinger-cache
    path: /cache
  settings:
    rebuild: true
    mount:
      - ./node_modules

- name: push-registry
  image: plugins/docker
  settings:
    repo: registry.max-heidinger.de/max-heidinger.de
    registry: registry.max-heidinger.de
    tags:
      - latest
      - ci-${DRONE_BUILD_NUMBER}
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password
  when:
    branch:
    - master
    - develop
    event:
      exclude:
      - pull_request

volumes:
- name: max-heidinger-cache
  host: 
    path: /tmp/max-heidinger-cache