kind: pipeline
name: default

steps:
- name: build-site
  image: node
  commands:
  - npm install
  - npm run build

- name: push-registry
  image: plugins/docker
  settings:
    repo: registry.max-heidinger.de/max-heidinger.de
    registry: registry.max-heidinger.de
    tags:
      - latest
      - ci-${DRONE_BUILD_NUMBER}
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password
  when:
    branch:
    - master
    - develop
    event:
      exclude:
      - pull_request