pipeline:
  publish-docker:
    image: plugins/docker
    repo: registry.max-heidinger.de/max-heidinger.de
    registry: registry.max-heidinger.de
    secrets: [ docker_username, docker_password ]
    tags: latest
    when:
      branch: master
      event: push

  rancher-deploy:
    image: peloton/drone-rancher
    url: https://max-heidinger.de:8089
    secrets: [ rancher_access_key, rancher_secret_key ]
    service: websites/max-heidinger
    docker_image: registry.max-heidinger.de/max-heidinger.de
    when:
      branch: master
      event: push