kind: pipeline
name: default

steps:
- name: build-site
  image: node
  commands:
  - npm install
  - npm run build

- name: push-registry
  image: plugins/docker
  settings:
    repo: registry.glidingthrough.space/max-heidinger.de
    registry: registry.glidingthrough.space
    tags:
      - latest
      - ci-${DRONE_BUILD_NUMBER}
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password
  when:
    branch:
    - master
    - develop
    event:
      exclude:
      - pull_request

- name: deploy-image
  image: quay.io/riesinger/drone-kubernetes
  settings:
    kubernetes_server:
      from_secret: kubernetes_apiserver
    kubernetes_token:
      from_secret: kubernetes_token
    kubernetes_cert:
      from_secret: kubernetes_cert
    kubernetes_user: drone-max-deployments
    namespace: max
    deployment: max-heidinger
    container: max-heidinger
    repo: registry.glidingthrough.space/max-heidinger.de
    tag: ci-${DRONE_BUILD_NUMBER}
  when:
    branch:
      - master
    event:
      exclude:
      - pull_request