pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/websiteCache:/cache
  
  build-site:
    image: node:9-slim
    commands:
      - yarn
      - yarn build

  publish-docker:
    image: plugins/docker
    repo: registry.max-heidinger.de/max-heidinger.de
    registry: registry.max-heidinger.de
    secrets: [ docker_username, docker_password ]
    tags: latest
    when:
      branch: master
      event: push

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/websiteCache:/cache